# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_dmvn <- function(x, Sigma) {
    .Call('_spBART4_log_dmvn', PACKAGE = 'spBART4', x, Sigma)
}

bspline <- function(x, x_obs) {
    .Call('_spBART4_bspline', PACKAGE = 'spBART4', x, x_obs)
}

sbart <- function(x_train, y_train, x_test, xcut, B_train, B_test, D, n_tree, n_mcmc, n_burn, tau, mu, tau_mu, tau_b, tau_b_intercept, alpha, beta, a_tau, d_tau, nu, delta, a_delta, d_delta, a_tau_b, d_tau_b, p_sample, p_sample_levels, intercept_model, stump) {
    .Call('_spBART4_sbart', PACKAGE = 'spBART4', x_train, y_train, x_test, xcut, B_train, B_test, D, n_tree, n_mcmc, n_burn, tau, mu, tau_mu, tau_b, tau_b_intercept, alpha, beta, a_tau, d_tau, nu, delta, a_delta, d_delta, a_tau_b, d_tau_b, p_sample, p_sample_levels, intercept_model, stump)
}

rand_unif <- function() {
    .Call('_spBART4_rand_unif', PACKAGE = 'spBART4')
}

